### ISSUE TITLE
Implement ipfs-sync with TheGraph cluster

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-ipfs#5]
Based on conversation in https://github.com/dap-ps/discover/issues/42 we'll need a periodic sync with TheGraph IPFS cluster using their syncing script: [ipfs-sync](https://github.com/graphprotocol/ipfs-sync)

**Comment by jakubgs** [comment]
I deployed `ipfs-sync` in d0b29c20 but it doesn't seem to work:
```
admin@node-01.gc-us-central1-a.ipfs.prod:~ % sudo -u nobody /usr/local/bin/ipfs-sync
Syncing files
Source node (--from): http://localhost:9095/
Target node (--to): https://api.thegraph.com/ipfs/
/opt/ipfs-sync/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

    at parseError (/opt/ipfs-sync/node_modules/ipfs-http-client/src/utils/send-request.js:22:17)
    at ClientRequest.<anonymous> (/opt/ipfs-sync/node_modules/ipfs-http-client/src/utils/send-request.js:64:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11) {
  statusCode: 502
}
```

**Comment by jakubgs** [comment]
The timer triggered the service that worked overnight:
```
sudo journalctl -au ipfs-sync.service
```
```
Syncing files
Source node (--from): http://localhost:9095/
Target node (--to): https://api.thegraph.com/ipfs/
404 files need to be synced
---
0/404 (QmNMBjf8KU1xjsSXff44L4HKQjssnwdyt4w2bMjyVFg5NZ): Syncing
0/404 (QmNMBjf8KU1xjsSXff44L4HKQjssnwdyt4w2bMjyVFg5NZ): Retrieving file
1/404 (QmNQ5E7cwSErYMbkZAD9eYN5nicWptC9vSuziD6EArwXFw): Syncing
1/404 (QmNQ5E7cwSErYMbkZAD9eYN5nicWptC9vSuziD6EArwXFw): Retrieving file
2/404 (QmNR2JwRpB2ZwUyPco7zf2KbGSUni1fEUS65hR9GUpNxCr): Syncing
2/404 (QmNR2JwRpB2ZwUyPco7zf2KbGSUni1fEUS65hR9GUpNxCr): Retrieving file
...(omitted)...
400/404 (QmfQSGnYVj8D6EUHjpMCJUcvv5iy3UZZQz1D7P1QmnKGXS): Uploading file
403/404 (QmfZp8gzRrGHTPPXbCGWcjJiFmHpGjSzQWzm3iUKYWAUzY): Uploading file
401/404 (QmfRmsxMUBYNcpHHqmCJ5X3tkaqTu7foxghWyZ8jB4HUKw): Uploading file
402/404 (QmfSVWmdw36EY3qH4VLLeup18mWBrCQCkF99FEXGEDP9DX): Uploading file
400/404 (QmfQSGnYVj8D6EUHjpMCJUcvv5iy3UZZQz1D7P1QmnKGXS): File synced successfully
403/404 (QmfZp8gzRrGHTPPXbCGWcjJiFmHpGjSzQWzm3iUKYWAUzY): File synced successfully
401/404 (QmfRmsxMUBYNcpHHqmCJ5X3tkaqTu7foxghWyZ8jB4HUKw): File synced successfully
402/404 (QmfSVWmdw36EY3qH4VLLeup18mWBrCQCkF99FEXGEDP9DX): File synced successfully
---
404/404 files synced
0 skipped (directories)
0 failed
```
Now it says there's nothing left to sync:
```
 $ sudo -u nobody /usr/local/bin/ipfs-sync
Syncing files
Source node (--from): http://localhost:9095/
Target node (--to): https://api.thegraph.com/ipfs/
0 files need to be synced
---
0/0 files synced
0 skipped (directories)
0 failed
```
So I consider this done.
